### ISSUE TITLE
[Bug] Does not work on Windows 10 17763

### ISSUE THREAD

**Issue by hugmouse** [e6Hub/app#1]
**What is the bug?**
Release version does not work. Nothing in the logs after start-up, but 30% of the CPU is consumed all the time.

**Steps to reproduce that**
1. Download this release - https://github.com/e6Hub/app/releases/download/v3.2.0/e6Hub-Setup-3.2.0.exe
2. Install it
3. Run it

**Machine info**
* OS: Windows 10 (10.0.17763)
* App version: 3.2.0 a9286d5cf840dc861a352a447adf210b8024c39b

![mintty_q724wOXcA4](https://user-images.githubusercontent.com/44648612/71420145-8e319300-26ae-11ea-94f5-1a0ab517b27f.png)

**Comment by xaeky** [comment]
try using the `--debug` flag through cmd and see what is wrong there

**Comment by hugmouse** [comment]
Tested on two different systems - the result is the same

![windows 10 LTSC](https://user-images.githubusercontent.com/44648612/71467530-1b373200-27fe-11ea-8a5a-18a13e8fa516.png)

![windows 10 server](https://user-images.githubusercontent.com/44648612/71467815-fabba780-27fe-11ea-87b5-28a91c2e629a.png)

**Comment by xaeky** [comment]
The issue was identified.
* CPU load is caused by the DiscordRPC at function `connectRPC()`, it makes a loop.
https://github.com/e6Hub/app/blob/4af2b63124e45af1964ba516b72ed9cb06071ac5/src/background.js#L133-L135
* The launch is something else (only for Windows 10), there's an async function at `ready` event preventing app's launch.
https://github.com/e6Hub/app/blob/4af2b63124e45af1964ba516b72ed9cb06071ac5/src/background.js#L45-L46

I'll fix those issues ASAP.

**Comment by hugmouse** [comment]
It works now, thanks!
